services:

  backend:
    build:
      context: .docker
      args:
        - NODE_MAJOR=${NODE_MAJOR:-20}
    ports:
      - "127.0.0.1:${HTTP_PORT:-80}:3000"
      - "127.0.0.1:${HTTP_PORT:-8080}:3001"
    volumes:
      - .:/var/www/html
    environment:
      - HOST_UID=${HOST_UID:-1000}
      - HOST_GID=${HOST_GID:-1000}
      - TZ=${TZ:-America/Sao_Paulo}
      - XDEBUG_CONFIG=${XDEBUG_CONFIG:-client_host=172.17.0.1 start_with_request=yes}
      - XDEBUG_MODE=${XDEBUG_MODE:-debug}
      - APP_ENV=${APP_ENV:-develop}
